homepage:
    path: /
    controller: MagicFramework\Controller\HomeController::homepage

blog:
    path: /blog/{year}/{month}/{day}
    controller: MagicFramework\Controller\BlogController::view
    requirements:
        year: \d+
        month: \d+
        day: \d+
